name: Update Gold Price and Images

on:
  schedule:
    - cron: '0/15 * * * *' # প্রতি ১ ঘণ্টা পর পর অটো রান হবে
  workflow_dispatch:     # ম্যানুয়ালি রান করার অপশন

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Firebase Service Account Key
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          if [ -n "$FIREBASE_KEY" ]; then
            echo "$FIREBASE_KEY" > serviceAccountKey.json
          fi

      - name: Run Main Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py

      - name: Commit and Push Updated Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add thermal_print.png color_price.png last_price.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update gold price and images [skip ci]" && git push)
